### ISSUE TITLE
PDF Uploaded successfully to container, no index created and no PDF listed in DropDown

### ISSUE THREAD

**Issue by PrintsCharming** [akshata29/chatpdf#11]
I can successfully upload a PDF. I can see the file in the container. 

However...

In the search service no index exists and no PDFs exist in the drop down in the Developer settings.
No errors listed in AppInsights.

Any suggestions as to where to start to look?

**Comment by akshata29** [comment]
Assuming you meant Cognitive search as in search service.  Also assuming you selected Cog Search in dropdown at the time of uploading/indexing.  If so, you can turn on live-metrics in app insights and that will show you the details.  Alternatively you can open up the Function App -> Functions -> Doc Generator -> Monitor and it will show you the logs for the last run with some debug information.

**Comment by PrintsCharming** [comment]
Ok getting closer. It was a miss on my part not seeing the Index Type Drop Down.

It now creates a Azure Cog Search index, which I can see the contents of in the Azure Portal.

I still cannot see any Documents in the Document Drop Down in the Developer Settings...the Refresh Button does not resolve it.

SQL NLP works...so that seems to be wired up ok.

Speech Analysis doesn't record, though your deployment does...so there must be something disconnected there too...

I'll re-check all my Configurations in the App and Funcs

**Comment by akshata29** [comment]
> Ok getting closer. It was a miss on my part not seeing the Index Type Drop Down.
> 
> It now creates a Azure Cog Search index, which I can see the contents of in the Azure Portal.
> 
> I still cannot see any Documents in the Document Drop Down in the Developer Settings...the Refresh Button does not resolve it.

The only reason that it may show up in "Documents Drop down is in case of "Qa" & Summary metadata is missing.  I found that bug yesterday and will fix it.  But if you go to your Storage container where the file was uploaded and if you select your file, you will see metadata attached to each file (indexType, indexNs, Qa, Summary, embed and others).  For now if you just enter qa and summary metadata with "blank" value, it will show up. Of course, feel free to create pull request and make the changes if you want to

> SQL NLP works...so that seems to be wired up ok.
> 
> Speech Analysis doesn't record, though your deployment does...so there must be something disconnected there too...
Confirm that speech analytics region & key are entered and that the browser allows recording from microphone. 

> I'll re-check all my Configurations in the App and Funcs

**Comment by akshata29** [comment]
Bug fixed.
