### ISSUE TITLE
Clean Deploy To Azure

### ISSUE THREAD

**Issue by PrintsCharming** [akshata29/chatpdf#13]
Using the deploy script, and button in the Documentation, I cannot get a clean deploy. One to two resources fail to deploy every time. It's not always the same resources, but typically it's one of the chat model deployments.

The typical error is 'Conflict' but occasionally 'Bad Request'

Is there a best practice for getting this to deploy with the script?

**Comment by akshata29** [comment]
It seems to be more of Timing issue, but if you are using  "Deploy to Azure" script, the first time it's been failing on Function host default key (which seems to be known issue) and when it's trying to create the OAI models.  But if you re-deploy it, even with error second time all is successfully deployed.

**Comment by akshata29** [comment]
Closing the issue as seems as duplicate to other that is opened

**Comment by MediGenie** [comment]
So I am having the same issue when deploying with the AZURE script. I re-deployed it 3 times but i get the same error. help? :)

"
Another operation is being performed on the parent resource '/subscriptions/50f2142a-e51a-449c-ac1e-1211c5ef33cf/resourceGroups/Ssap/providers/Microsoft.CognitiveServices/accounts/ssapaoai'. Please try again later. Click here for details"
