### ISSUE TITLE
Circular dependency detected 

### ISSUE THREAD

**Issue by PrintsCharming** [akshata29/chatpdf#15]
I've done a few deploys with the automation scripts previously, however all of a sudden I'm getting the following when attempting to run:

{"code":"InvalidTemplate","message":"Deployment template validation failed: 'Circular dependency detected on resource: '/subscriptions/MYSUBSCRIPTIONID/resourceGroups/rcshrchatdemo/providers/Microsoft.Web/sites/rcshrchatfunc'. Please see https://aka.ms/arm-syntax-resources for usage details.'."}

I've tried numerous Resource Group Name and Prefix combinations. I've ensured all my other deploys where cleanly deleted. And have updated my fork with the latest here.

Not sure what else to try.

**Comment by akshata29** [comment]
My bad, found the bug and fixing it, Will close the issue upon bug fix and quick testing.

**Comment by akshata29** [comment]
@PrintsCharming  - Fixed. Let me know if any further issues.
