### ISSUE TITLE
Module Not Found 'azure.ai'

### ISSUE THREAD

**Issue by PrintsCharming** [akshata29/chatpdf#18]
I'm receiving the following error when processing documents. This is seemingly related to Form Recognizer, regardless if I use it or not. 

`Exception while executing function: Functions.DocGenerator <--- Result: Failure Exception: ModuleNotFoundError: No module named 'azure.ai'. Please check the requirements.txt file for the missing module. For more info, please refer the troubleshooting guide: https://aka.ms/functions-modulenotfound Stack: File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 374, in _handle__function_load_request func = loader.load_function( File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 48, in call raise extend_exception_message(e, message) File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 44, in call return func(*args, **kwargs) File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/loader.py", line 132, in load_function mod = importlib.import_module(fullmodname) File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/home/site/wwwroot/DocGenerator/__init__.py", line 28, in <module> from Utilities.formrecognizer import analyze_layout, chunk_paragraphs File "/home/site/wwwroot/Utilities/formrecognizer.py", line 1, in <module> from azure.ai.formrecognizer import DocumentAnalysisClient `

**Comment by akshata29** [comment]
Thank you.  Updated the requirements.txt file with FR module.
