### ISSUE TITLE
[Feature Request] Env for switching Azure and OpenAI

### ISSUE THREAD

**Issue by ac1982** [akshata29/chatpdf#2]
Could you please add an environment variable to enable switching between the Azure and OpenAI APIs? Thank you.

**Comment by rossman22590** [comment]
Please PLEASE do this :)

**Comment by akshata29** [comment]
Currently working on supporting and switching between Azure and OpenAI for both embedding as well as LLM/Completion.  Eventually will add capability to support Hugging face OSS models too.

**Comment by akshata29** [comment]
@rossman22590 - Support for switching between Azure and OpenAI is available.  Will add backlog for Huggingface OSS models shortly
