### ISSUE TITLE
Other language support?

### ISSUE THREAD

**Issue by MediGenie** [akshata29/chatpdf#21]
Hey is there a way i can ask questions and get answers back in Korean? Regardless whether the document is Korean or not?

**Comment by akshata29** [comment]
@MediGenie  - I did some basic testing and the current implementation should work as far as you asked the question in Korean, it is responding back in that too.   I can certainly provide option/dropdown in UI to select language if that's easier

![image](https://github.com/akshata29/chatpdf/assets/18509807/73625823-7784-4f85-8373-7e95b26537e7)

**Comment by akshata29** [comment]
Closing the issue will add feature request for additional language support

**Comment by MediGenie** [comment]
Thank you!
