### ISSUE TITLE
Long Response Time / high latency

### ISSUE THREAD

**Issue by MediGenie** [akshata29/chatpdf#23]
So I am based in Seoul, South Korea. I know Azure OpenAI/OpenAI resources are only based in US/Europe and not Asia yet, but for people in US East/US Central are you guys experiencing high latency or long time to respond?

For me i brought Azure resources that i can and Pinecone to Korea Central, but I am wondering @akshata29 what are some other things or ideas you can think of that I can do to speed things up on my end? Not taking cost into a factor. I just want chatpdf to run fast like https://chatpdf.com/

Thank you!!

**Comment by akshata29** [comment]
At times I do see some latency issue in US, but most of the time have not run into the issue.   Depending on your use-case, you can implement the Cache mechanism (I have that in list to implement it) and/or build your own KB to not call OpenAI all the time based on the KB you are building on your document/data

**Comment by akshata29** [comment]
Implemented the Cache pattern (using Cognitive search) in the repo.  Moreover you can now also implement pattern as per the reference architecture we created at https://learn.microsoft.com/en-us/azure/architecture/example-scenario/ai/log-monitor-azure-openai to load-balance against multiple AOAI instance.  Lastly for enterprise customers, we do allow PTU (Provisioned Throughput) model to get the latency and performance metrics.
