### ISSUE TITLE
using "Deploy to Azure" encounter errors

### ISSUE THREAD

**Issue by cyberflying** [akshata29/chatpdf#25]
1. error message: **The capacity should be null for standard deployment.**
it seems due to **”capacity": 20** when deploy /chat, /davinci, /text-embedding-ada-002. 
remove capacity then works.
<img width="936" alt="image" src="https://github.com/akshata29/chatpdf/assets/6263170/7e55ca52-7a3a-4f26-bd9f-22b7b104ad84">

2.error message: **Another operation is being performed on the parent resource '/subscriptions/9dabf3b5-95af-489f-8423-ae43e4b1707c/resourceGroups/rg-aoai-chatpdf/providers/Microsoft.CognitiveServices/accounts/kevingptaoai'. Please try again later. (Code: RequestConflict)**
it seems can not deploy the 3 model: chat, davinci and text-embedding-ada-002 in parallel. 
refer to this blog: https://techcommunity.microsoft.com/t5/azure-database-support-blog/add-wait-operation-to-arm-template-deployment/ba-p/2915342#:~:text=How%20can%20an%20ARM%20JSON%20template%20be%20forced,to%20set%20the%20dependencies%20of%20the%20steps%20correctly
I can fix this error such as:
`{
    "type": "Microsoft.CognitiveServices/accounts/deployments",
    "apiVersion": "2022-12-01",
    "name": "[concat(variables('aoaiSvcName'), '/chat')]",
    "dependsOn": [
        "[resourceId('Microsoft.CognitiveServices/accounts', variables('aoaiSvcName'))]"
    ],
    "properties": {
        "model": {
            "format": "OpenAI",
            "name": "gpt-35-turbo",
            "version": "0301"
        },
        "scaleSettings": {
            "scaleType": "Standard"
        },
        "raiPolicyName": "Microsoft.Default"
    }
},
{
    "type": "Microsoft.Resources/deploymentScripts",
    "apiVersion": "2020-10-01",
    "kind": "AzurePowerShell",
    "name": "Wait5s",
    "location": "[parameters('location')]",
    "dependsOn": [
        "[resourceId('Microsoft.CognitiveServices/accounts', variables('aoaiSvcName'))]"
            ],
    "properties": {
        "azPowerShellVersion": "9.7",
        "scriptContent": "start-sleep -Seconds 5",
        "cleanupPreference": "Always",
        "retentionInterval": "PT1H"
    }
},
{
    "type": "Microsoft.CognitiveServices/accounts/deployments",
    "apiVersion": "2022-12-01",
    "name": "[concat(variables('aoaiSvcName'), '/davinci')]",
    "dependsOn": [
        "[resourceId('Microsoft.Resources/deploymentScripts','Wait5s')]"
    ],
    "properties": {
        "model": {
            "format": "OpenAI",
            "name": "text-davinci-003",
            "version": "1"
        },
        "scaleSettings": {
            "scaleType": "Standard"
        },
        "raiPolicyName": "Microsoft.Default"
    }
},
{
    "type": "Microsoft.Resources/deploymentScripts",
    "apiVersion": "2020-10-01",
    "kind": "AzurePowerShell",
    "name": "Wait10s",
    "location": "[parameters('location')]",
    "dependsOn": [
        "[resourceId('Microsoft.CognitiveServices/accounts', variables('aoaiSvcName'))]"
            ],
    "properties": {
        "azPowerShellVersion": "9.7",
        "scriptContent": "start-sleep -Seconds 10",
        "cleanupPreference": "Always",
        "retentionInterval": "PT1H"
    }
},
{
    "type": "Microsoft.CognitiveServices/accounts/deployments",
    "apiVersion": "2022-12-01",
    "name": "[concat(variables('aoaiSvcName'), '/text-embedding-ada-002')]",
    "dependsOn": [
        "[resourceId('Microsoft.Resources/deploymentScripts','Wait10s')]"
    ],
    "properties": {
        "model": {
            "format": "OpenAI",
            "name": "text-embedding-ada-002",
            "version": "2"
        },
        "scaleSettings": {
            "scaleType": "Standard"
        },
        "raiPolicyName": "Microsoft.Default"
    }
}`

3. error message: **Encountered an error (InternalServerError) from host runtime.**
I try many times, but finally report this error when deploying <prefix>func/default
<img width="1361" alt="image" src="https://github.com/akshata29/chatpdf/assets/6263170/ee9eaa67-35ae-4185-93d2-f349bd6346ae">
I cannot find detail error information, hope can get your help on this issue.

4. redeploy button cannot re-run, if click redeploy button, it'll back to the page of:
<img width="653" alt="image" src="https://github.com/akshata29/chatpdf/assets/6263170/68b1a15d-5fd6-419f-a83c-57b0d408553c">
then it will report many conflict errors

5. Bing resource always report error
I test and create Bing resource alonely, it report error: (ApiSetDisabledForCreation) It's not allowed to create new accounts with type 'Bing.Search.v7'.
So, I removed the Bing resource. Could you help check and confirm if it is possible to create Bing resources? and what happens to this repo demo if don't create bing resource?

Thanks!
Kevin

**Comment by akshata29** [comment]
Thank you Kevin, appreciate your help.  I did fix the OpenAI, capacity and the "timing" issue code that you provided.   For #3 the issue I see (which am not able to figure it out) is more around the timing on setting the configuration values in the Azure function.  I have not deployed fully, so will test it ou, but #3 and #4 are tied together as it should still allow you to redeploy (provided it's same prefix and parameters).   As to #5, it looks that your subscription is not enable for creating Bing API and it's perfectly fine for you to not create that as the only feature that uses (in current state) Bing API is "Smart Agent", so if you don't deploy that everything but that will still continue to work.

**Comment by cyberflying** [comment]
Thank you, Ashish!
hope you can reproduce the issue #3, #4 when fully deployed.  :)
