### ISSUE TITLE
Capacity error when Repdeploying

### ISSUE THREAD

**Issue by PrintsCharming** [akshata29/chatpdf#28]
Upon trying to redeploy after receiving the error mentioned in #26 I am now getting this validation error:

`{"code":"InvalidTemplateDeployment","details":[{"code":"InsufficientQuota","message":"The specified capacity '120' of account deployment is bigger than available capacity '0' for UsageName 'Tokens Per Minute (thousands) - GPT-35-Turbo'."}],"message":"The template deployment 'Microsoft.Template-20230630090235' is not valid according to the validation procedure. The tracking id is '072a60c3-87f9-4f1e-95e3-f4a259595e09'. See inner errors for details."}`

Any advice?

**Comment by akshata29** [comment]
Is there already a deployment for gpt35 turbo model on that same AOAI instance?.  If so you may have to manually adjust that existing deployment to lower#.  Let me try to replicate the issue on my end.

**Comment by PrintsCharming** [comment]
I just redeployed having not touched the project over the weekend and it worked fine...

Earlier I had an issue with purging soft deletes...I wonder if it was related.

**Comment by akshata29** [comment]
Perfect - Will close the issue for now
