### ISSUE TITLE
Some AOAI Model have been retirements.

### ISSUE THREAD

**Issue by niceysj** [akshata29/chatpdf#30]
I tried to proceed with the deployment today, and it returned the following error message.

{"code":"InvalidTemplateDeployment","details":[{"code":"DeploymentModelNotSupported","message":"Creating account deployment is not supported by the model 'text-davinci-003'. This is usually because there are better models available for the similar functionality."}],"message":"The template deployment 'Microsoft.Template-20230710120955' is not valid according to the validation procedure. The tracking id is 'af2ae21d-44e5-4cf7-a186-32577951880f'. See inner errors for details."}

Checked through the following link and found that there was a Model change.
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/models

I'd like to ask you to change code.

**Comment by kalchakra13** [comment]
Faced same problem, tried to switch to gpt-35-turbo-16k and facing issues.

**Comment by niceysj** [comment]
Deployment has been successful since I deleted the Davinci deployment code to resolve issues with replacing the AOAI model.

**Comment by kalchakra13** [comment]
which model did you replace it with?

**Comment by akshata29** [comment]
> Deployment has been successful since I deleted the Davinci deployment code to resolve issues with replacing the AOAI model.

Would you mind creating pull request and fixing azuredeploy.json file?  Happy to modify code if you can suggest the fix

**Comment by niceysj** [comment]
> > Deployment has been successful since I deleted the Davinci deployment code to resolve issues with replacing the AOAI model.
> 
> Would you mind creating pull request and fixing azuredeploy.json file? Happy to modify code if you can suggest the fix
Sure, I've modified the code, and hope you'll review it.

**Comment by niceysj** [comment]
Sorry about that. 
I thought I had made a pull request, but I guess it wasn't requested.
I'm not very skilled with github.
I'll try to explain in the comments. 
In the file below, I removed the following Davinci model from the deployment.
azuredeploy.json
 {
            "type": "Microsoft.CognitiveServices/accounts/deployments",
            "apiVersion": "2022-12-01",
            "name": "[concat(variables('aoaiSvcName'), '/davinci')]",
            "dependsOn": [
                "[resourceId('Microsoft.Resources/deploymentScripts','Wait5s')]"
            ],
            "properties": {
                "model": {
                    "format": "OpenAI",
                    "name": "text-davinci-003",
                    "version": "1"
                },
                "scaleSettings": {
                    "scaleType": "Standard"
                },
                "raiPolicyName": "Microsoft.Default"
            }


And delete the following parts.
{
			  "name": "OpenAiDavinci",
			  "value": "davinci"
			},

Please review this.

**Comment by akshata29** [comment]
Modified the deployment to remove the Davinci model usage and replace it with only gpt3.5 turbo, embedding and 3.5turbo with 16k model.   All code using Davinci is also refactored
