### ISSUE TITLE
web app display: Authentication Not Configured

### ISSUE THREAD

**Issue by cyberflying** [akshata29/chatpdf#31]
after sync fork and rerun the action workflow: Deploy Python API and Deploy App, when access the web site, it display 
<img width="1607" alt="image" src="https://github.com/akshata29/chatpdf/assets/6263170/0b32e3f0-12ca-4898-9902-411f18baf578">

I found only 3 tabs have this issue: Chat, Ask a question and PIB.

**Comment by akshata29** [comment]
That's by design.  Introduced a way to secure the website (and selected features) as that was ask.   I will change the message to be more clear, but for those feature in current state you will have to deploy in your tenant and will provide instruction on how to configure that.

**Comment by cyberflying** [comment]
> 

got it, thanks!

**Comment by Mshz2** [comment]
@akshata29 Thanks for the support. Is there anyway to disable the authentication feature above?

**Comment by cyberflying** [comment]
> 

I followed this doc, it could allow AAD user to access the website:
https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-authentication-app-service#3-configure-authentication-and-authorization

**Comment by akshata29** [comment]
> @akshata29 Thanks for the support. Is there anyway to disable the authentication feature above?
> 
> @cyberflying can I please ask if you found any work-around to diasble authentication ?

Thanks @cyberflying.

@Mshz2 
If you want to disable the authentication by itself, the core code are in ChatGpt.tsx, OneShot.tsx and Pib.tsx.  For each of those in the useEffect method, comment following lines of code

 if (window.location.hostname != "localhost") {
            getUserInfoList();
            setShowAuthMessage(true)
        } else
            setShowAuthMessage(false)
