### ISSUE TITLE
Deploying with azd up is not creating full resources

### ISSUE THREAD

**Issue by Mshz2** [akshata29/chatpdf#34]
Hi, thanks for sharing your project with us. I tried to clone, and deploy the project by following commands of azd init, azd up. And I can access my app main page. But I noticed not all resources are fully deployed. For instance if I open main.bicep and go end of line, we see:
![image](https://github.com/akshata29/chatpdf/assets/63469924/6e8a8348-eb1c-482c-b97e-4ae94136b9a1)

Which means only app service plan, app service, function app, cognitive search, two storage accounts, and Azure openai services are created. Is there anyway that I could make sure all resources are fully deployed?

Best

**Comment by akshata29** [comment]
Hello Majid in the current state I am not supporting or have update the deployment using azd.  Instead the recommended approach is as described in "Getting Started" section on using "Deploy to Azure" button for infrastructure deployment and using the Github Actions to deploy the code for both App and Azure Functions.  Let me know if you run into any issues there.

**Comment by Mshz2** [comment]
Dear @akshata29, thanks for the feedback. I have followed the Deploy to Azure botton, and all services and resources are deployed, unfortunately except a resource called chatpdfcustomfunc/default.

![image](https://github.com/akshata29/chatpdf/assets/63469924/24bd309e-66b9-4090-92dc-3ac7d7975c95)

{"code":"BadRequest","message":"Encountered an error (InternalServerError) from host runtime.","details":[{"message":"Encountered an error (InternalServerError) from host runtime."},{"code":"BadRequest"},{}]}

**Comment by Mshz2** [comment]
I looked at azuredeploy.json, actually there was duplicate of             
```
{
  "name": "SQLVISUAL_URL",
  "value": "[concat('https://', variables('funcAppName'), '.azurewebsites.net/api/SqlVisual?code=', listkeys(concat(resourceId('Microsoft.Web/sites', variables('funcAppName')), '/host/default'), '2018-11-01').functionKeys.default)]" 
 },

```
issue solved by deletion of duplicated one.
