### ISSUE TITLE
OPEN AI ISSUE 

### ISSUE THREAD

**Issue by rehat22** [akshata29/chatpdf#36]
When i deploy the template on azure, it gives the following error
 {"code":"InvalidTemplateDeployment","details":[{"code":"DeploymentModelNotSupported","message":"The model 'Format: OpenAI, Name: embedding, Version: 2, Source: ' of account deployment is not supported."}],"message":"The template deployment 'Microsoft.Template-20230809000923' is not valid according to the validation procedure. The tracking id is 'd3e1e7eb-221a-4e44-a8f1-5a7583a5f191'. See inner errors for details."}

**Comment by akshata29** [comment]
Thank you @rehat22, fixed the deployment bug and you should be good to redploy using same parameters that you initially selected.

**Comment by rehat22** [comment]
@akshata29  thank you!
