### ISSUE TITLE
Azure Function BackEnd endpoint access not working.

### ISSUE THREAD

**Issue by niceysj** [akshata29/chatpdf#6]
I installed the required programmes on Windows 10 21H2 x64 and executed the source code.
Everything was executed normally until the azd up command, but when accessing the Backend Endpoint created in Azure apps, the following error is returned.
"Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."

Everything ran fine until azd up and the logs are as follows.
==================================================================================
C:\Users\niceysj\repo\chatgptspk\chatpdf>azd up

Packaging services (azd package)

  (✓) Done: Packaging service backend
  - Package Output: C:\Users\niceysj\AppData\Local\Temp\azddeploy2270936496.zip
  (✓) Done: Packaging service functionapp
  - Package Output: C:\Users\niceysj\AppData\Local\Temp\azddeploy1938513666.zip

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2F3e5e369f-3d6e-4c3f-87f4-83c1cca16cb5%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Fchatgptspk

  (✓) Done: Resource group: chatspk
  (✓) Done: Application Insights: chatspkappisg
  (✓) Done: App Service plan: chatspkasp
  (✓) Done: Storage account: chatspkstor
  (✓) Done: Storage account: chatspkfuncsa
  (✓) Done: Function App: chatspkfunc
  (✓) Done: Search service: chatspkazs
  (✓) Done: Azure OpenAI: chatspkoai
  (✓) Done: App Service: chatspkbackend

Executing predeploy hook => C:\Users\niceysj\AppData\Local\Temp\azd-predeploy-1027173797.ps1
npm WARN deprecated redux-devtools-extension@2.13.9: Package moved to @redux-devtools/extension.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@3.12.1: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@3.15.2: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@3.18.3: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 589 packages, and audited 590 packages in 1m

59 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

> chatpdf@0.0.0 build
> tsc && vite build --mode prod

vite v4.1.1 building for prod...
✓ 2703 modules transformed.
../backend/static/index.html                      0.46 kB
../backend/static/assets/github-fab00c2d.svg      0.96 kB
../backend/static/assets/index-d593fb67.css      16.45 kB │ gzip:   2.90 kB
../backend/static/assets/index-4215e6c8.js    1,185.83 kB │ gzip: 348.14 kB │ map: 10,008.16 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

Deploying services (azd deploy)

  (✓) Done: Deploying service backend
  - Endpoint: https://chatspkbackend.azurewebsites.net/

  (✓) Done: Deploying service functionapp
  - Endpoint: https://chatspkfunc.azurewebsites.net/

SUCCESS: Your Azure app has been deployed!
You can view the resources created under the resource group chatspk in Azure Portal:
https://portal.azure.com/#@/resource/subscriptions/3e5e369f-3d6e-4c3f-87f4-83c1cca16cb5/resourceGroups/chatspk/overview

C:\Users\niceysj\repo\chatgptspk\chatpdf>npm audit fix

added 93 packages, and audited 94 packages in 3s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by akshata29** [comment]
At times we are seeing inconsistent behavior on the deployment and trying to figure that out.  Alternatively, we are going to allow users to deploy via "Deploy to Azure" button that we hope will be released soon

**Comment by niceysj** [comment]
I look forward to seeing your feature updated.
Thank you.
