### ISSUE TITLE
How can use this function: "4/13/2023 - Added new functionality to support questioning multiple documents using the Vector QA agent" ?

### ISSUE THREAD

**Issue by ShadowDawnme** [akshata29/chatpdf#8]

**Comment by akshata29** [comment]
Following are the steps :
1) Go to the deployed (or locally running) webapp
2) Select SQL NLP
3) Select Agent QA
4) Assuming the documents are uploaded, select the index (pinecone or redis).  That should filter all the documents you have uploaded in that specific vectorstore.
5) Select one or multiple documents from the list of all documents
6) Start asking question from those multiple documents.  It will interact with your data in the vectorstore in agentic manner.  Details about that is further available at https://python.langchain.com/en/latest/modules/agents/agent_executors/examples/agent_vectorstore.html

**Comment by akshata29** [comment]
Closing - Assuming the instructions/steps are helpful
